# -*- coding: utf-8 -*-
"""ML_project_Air_pollution (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCVJ_1sMx1iGq7EX8YUHcOFHBiliB9sU
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/sdg3_airpollution_u5mr/data_raw/who_pm25_2022.csv"
who_raw = pd.read_csv(path)

print(who_raw.columns)

who_raw.head()

who = who_raw.rename(columns={
    'Location': 'Country',
    'Period': 'Year',
    'Value': 'Value',
    'Indicator': 'Indicator',
    'Dim1': 'Category'
})

who.head()

if 'Category' in who.columns:
    who = who[who['Category'].str.contains('Total', case=False, na=False)]

who = who[who['Indicator'].str.contains('PM2.5|NO2', case=False, na=False)]

who['Country'] = who['Country'].str.strip()
who = who.dropna(subset=['Value'])

who['Year'] = who['Year'].astype(int)
who['Value'] = who['Value'].str.extract(r'(\d+\.?\d*)').astype(float)

who_pivot = who.pivot_table(
    index=['Country', 'Year'],
    columns='Indicator',
    values='Value'
).reset_index()

who_pivot.columns.name = None
who_pivot.columns = [col.replace(' ', '_').replace('(', '').replace(')', '') for col in who_pivot.columns]

print(who_pivot.head())

import pandas as pd
!pip -q install country_converter
import country_converter as coco
import re

base = "/content/drive/MyDrive/sdg3_airpollution_u5mr"
raw_path   = f"{base}/data_raw/who_pm25_2022.csv"
final_long = f"{base}/data_final/who_pm25_long.csv"
final_wide = f"{base}/data_final/who_pm25_wide.csv"

df_raw = pd.read_csv(raw_path, low_memory=False)
print("RAW shape:", df_raw.shape)
print(sorted(df_raw.columns.tolist())[:15], "...")

def pick(colnames):
    for c in colnames:
        if c in df_raw.columns:
            return c
    return None

COL_COUNTRY = pick(['Location','Country','SpatialDim','SpatialDimName'])
COL_YEAR    = pick(['Period','Year'])
COL_VALUE   = pick(['FactValueNumeric','Value','NumericValue'])
COL_IND     = pick(['Indicator','IndicatorName','Indicator Code','IndicatorCode'])

if not all([COL_COUNTRY, COL_YEAR, COL_VALUE]):
    raise ValueError(f"Missing a key column. Found -> Country:{COL_COUNTRY}, Year:{COL_YEAR}, Value:{COL_VALUE}")

# 3) Keep only PM2.5 rows
df = df_raw.copy()
if COL_IND and df[COL_IND].notna().any():
    pm_mask = df[COL_IND].astype(str).str.contains(r'PM2\.5|fine particulate', case=False, na=False)
    df = df[pm_mask].copy()

res_candidates = [c for c in df.columns if re.search(r'dim1|residence|urban|rural|total', c, flags=re.I)]
def detect_residence_column(frame, candidates):
    for c in candidates:
        vals = frame[c].astype(str).str.lower()
        if vals.str.contains('urban|rural|total', regex=True).any():
            return c
    return None

COL_RES = detect_residence_column(df, res_candidates)

def to_res(v):
    s = str(v).lower()
    if 'urban' in s: return 'Urban'
    if 'rural' in s: return 'Rural'
    if 'total' in s or 'national' in s or 'both sexes' in s: return 'Total'
    return None

if COL_RES:
    df['Residence'] = df[COL_RES].apply(to_res)
    df = df[df['Residence'].notna()]
else:
    df['Residence'] = 'Total'

df = df.rename(columns={COL_COUNTRY:'Country', COL_YEAR:'Year', COL_VALUE:'PM25_ugm3'})
df['Country'] = df['Country'].astype(str).str.strip()
df['Year'] = pd.to_numeric(df['Year'], errors='coerce').astype('Int64')
df['PM25_ugm3'] = pd.to_numeric(df['PM25_ugm3'], errors='coerce')
df = df.dropna(subset=['Country','Year','PM25_ugm3'])

if 'SpatialDimValueCode' in df.columns:
    iso = df['SpatialDimValueCode'].where(df['SpatialDimValueCode'].astype(str).str.len()==3)
else:
    iso = None
df['Country_ISO3'] = iso
fixes = {
    'Côte d’Ivoire': "Cote d'Ivoire",
    'Côte d\'Ivoire': "Cote d'Ivoire",
    'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
    'Congo, Rep.': 'Congo',
    'United States of America': 'United States',
    'Russian Federation': 'Russia',
    'Viet Nam': 'Vietnam',
}
need_iso = df['Country_ISO3'].isna()
df.loc[need_iso, 'Country_ISO3'] = coco.convert(df.loc[need_iso, 'Country'].replace(fixes), to='ISO3', not_found=None)

# 8) LONG (Country–Year–Residence)
who_long = (df[['Country','Country_ISO3','Year','Residence','PM25_ugm3']]
            .groupby(['Country','Country_ISO3','Year','Residence'], as_index=False)
            .agg({'PM25_ugm3':'mean'}))
print("LONG shape:", who_long.shape)
display(who_long.head(10))

who_wide = who_long.pivot_table(
    index=['Country','Country_ISO3','Year'],
    columns='Residence',
    values='PM25_ugm3',
    aggfunc='mean'
).reset_index()
who_wide.columns.name = None
who_wide = who_wide.rename(columns={'Rural':'PM25_Rural_ugm3',
                                    'Urban':'PM25_Urban_ugm3',
                                    'Total':'PM25_Total_ugm3'})
who_wide = who_wide.sort_values(['Country','Year']).reset_index(drop=True)
print("WIDE shape:", who_wide.shape)
display(who_wide.head(10))

who_long.to_csv(final_long, index=False)
who_wide.to_csv(final_wide, index=False)
print(f"Saved:\n  LONG -> {final_long}\n  WIDE -> {final_wide}")

import matplotlib.pyplot as plt

country = "Niger"
sub = who_wide[who_wide['Country'] == country]

plt.figure(figsize=(8,5))
plt.plot(sub['Year'], sub['PM25_Urban_ugm3'], marker='o', label='Urban')
plt.plot(sub['Year'], sub['PM25_Rural_ugm3'], marker='o', label='Rural')
plt.plot(sub['Year'], sub['PM25_Total_ugm3'], marker='o', label='Total')

plt.title(f"PM2.5 Levels Over Time - {country}")
plt.xlabel("Year")
plt.ylabel("PM2.5 (µg/m³)")
plt.legend()
plt.grid(True)
plt.show()

import seaborn as sns

plt.figure(figsize=(6,6))
sns.scatterplot(data=who_wide, x='PM25_Rural_ugm3', y='PM25_Urban_ugm3')
plt.plot([0,120],[0,120],'r--')  # reference line
plt.xlabel('Rural PM2.5 (µg/m³)')
plt.ylabel('Urban PM2.5 (µg/m³)')
plt.title('Urban vs Rural PM2.5 Concentration')
plt.show()

avg_pm25 = (who_wide.groupby('Country')['PM25_Total_ugm3']
            .mean().sort_values(ascending=False).head(10))

plt.figure(figsize=(10,5))
avg_pm25.plot(kind='bar', color='salmon')
plt.title("Top 10 Countries by Average PM2.5 (Total)")
plt.ylabel("PM2.5 (µg/m³)")
plt.xticks(rotation=45, ha='right')
plt.show()



who_wide['Urban_Rural_Gap'] = who_wide['PM25_Urban_ugm3'] - who_wide['PM25_Rural_ugm3']

gap = (who_wide.groupby('Country')['Urban_Rural_Gap']
       .mean().sort_values(ascending=False).head(10))

plt.figure(figsize=(10,5))
gap.plot(kind='bar', color='orange')
plt.title("Average Urban–Rural PM2.5 Gap (Top 10 Countries)")
plt.ylabel("Difference (µg/m³)")
plt.xticks(rotation=45, ha='right')
plt.show()

u5mr_path = "/content/drive/MyDrive/sdg3_airpollution_u5mr/data_raw/unicef_u5mr_2023.xlsx"

u5mr = pd.read_excel(u5mr_path)

print(u5mr.columns)
u5mr.head()

u5mr = u5mr[u5mr["Uncertainty.Bounds*"].astype(str).str.contains("Median", case=False, na=False)]

year_cols = [c for c in u5mr.columns if str(c).replace(".", "", 1).isdigit()]

u5mr_long = u5mr.melt(
    id_vars=["ISO.Code", "Country.Name"],
    value_vars=year_cols,
    var_name="Year",
    value_name="U5MR_per_1000"
)

u5mr_long["Year"] = pd.to_numeric(u5mr_long["Year"], errors="coerce").round().astype("Int64")
u5mr_long["U5MR_per_1000"] = pd.to_numeric(u5mr_long["U5MR_per_1000"], errors="coerce")
u5mr_long = u5mr_long.dropna(subset=["U5MR_per_1000"])

u5mr_long = u5mr_long.query("Year >= 1990")

u5mr_long = u5mr_long.rename(columns={
    "ISO.Code": "Country_ISO3",
    "Country.Name": "Country"
})

print("U5MR long shape:", u5mr_long.shape)
u5mr_long.head()

who_wide = pd.read_csv("/content/drive/MyDrive/sdg3_airpollution_u5mr/data_final/who_pm25_wide.csv")

who_wide["Year"] = pd.to_numeric(who_wide["Year"], errors="coerce").astype("Int64")

merged = pd.merge(
    who_wide,
    u5mr_long,
    on=["Country_ISO3", "Year"],
    how="inner"
)

print("Merged shape:", merged.shape)
merged.head()

import seaborn as sns
import matplotlib.pyplot as plt

corr = merged[["PM25_Total_ugm3", "PM25_Urban_ugm3", "PM25_Rural_ugm3", "U5MR_per_1000"]].corr()
print(corr.round(3))

plt.figure(figsize=(6,4))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix: PM2.5 vs Under-5 Mortality")
plt.show()

sns.regplot(data=merged, x="PM25_Total_ugm3", y="U5MR_per_1000", scatter_kws={"alpha":0.4})
plt.title("PM2.5 (Total) vs Under-5 Mortality Rate")
plt.xlabel("PM2.5 (µg/m³)")
plt.ylabel("Under-5 Mortality (per 1,000)")
plt.grid(True, alpha=0.3)
plt.show()

country = "Chad"
sub = merged[merged["Country_x"] == country].sort_values("Year")

fig, ax1 = plt.subplots(figsize=(8,5))
ax1.plot(sub["Year"], sub["PM25_Total_ugm3"], "b-o", label="PM2.5 Total")
ax1.set_xlabel("Year")
ax1.set_ylabel("PM2.5 (µg/m³)", color="b")

ax2 = ax1.twinx()
ax2.plot(sub["Year"], sub["U5MR_per_1000"], "r--s", label="U5MR")
ax2.set_ylabel("Under-5 Mortality (per 1,000)", color="r")

plt.title(f"{country}: PM2.5 and Under-5 Mortality Over Time")
plt.show()

import statsmodels.api as sm

# Simple linear regression: U5MR ~ PM2.5_Total
X = merged[["PM25_Total_ugm3"]]
y = merged["U5MR_per_1000"]
X = sm.add_constant(X)

model = sm.OLS(y, X, missing="drop").fit()
print(model.summary())

def load_ctrl_if_present(path, col_name):
    if not os.path.exists(path):
        print(f"[skip] {os.path.basename(path)} not found.")
        return None

    # robust CSV reader with encoding fallbacks
    encodings = [None, 'utf-8-sig', 'latin-1', 'cp1252']
    last_err = None
    for enc in encodings:
        try:
            df = pd.read_csv(path, encoding=enc, low_memory=False)
            if enc:
                print(f"[info] Loaded {os.path.basename(path)} with encoding={enc}")
            break
        except UnicodeDecodeError as e:
            last_err = e
    else:
        raise last_err  # if all encodings failed

    # ---- remainder unchanged ----
    if {'Country_ISO3','Year',col_name}.issubset(df.columns):
        out = df[['Country_ISO3','Year',col_name]].copy()
    else:
        year_cols = [c for c in df.columns if str(c).isdigit()]
        if not year_cols:
            print(f"[skip] {os.path.basename(path)} unexpected format.")
            return None
        out = (df.melt(id_vars=['Country_ISO3'], value_vars=year_cols,
                       var_name='Year', value_name=col_name)
                 .assign(Year=lambda d: pd.to_numeric(d['Year'], errors='coerce')))
    out = out.dropna(subset=[col_name])
    return out

print(df.columns.tolist())



# Build a robust 'work' dataset no matter if Country, Country_x, or Country_y exists
if 'df' not in locals():
    df = merged.copy()

pm_feats = [c for c in ['PM25_Total_ugm3','PM25_Urban_ugm3','PM25_Rural_ugm3'] if c in df.columns]
target   = 'U5MR_per_1000'

# collect whatever ID columns exist (do NOT require 'Country')
id_candidates = ['Country_ISO3','Year','Country','Country_x','Country_y']
id_cols = [c for c in id_candidates if c in df.columns]

# select safely
need_cols = list(dict.fromkeys(id_cols + [target] + pm_feats))
work = df[need_cols].copy()

# unify to a single 'Country' column if needed
if 'Country' not in work.columns:
    for c in ['Country_x','Country_y']:
        if c in work.columns:
            work['Country'] = work[c]
            break

# final clean
work = work.dropna(subset=[target] + pm_feats)

print("Using columns:", work.columns.tolist())
print("Rows:", len(work))

# ==== Predict U5MR from PM2.5 with a time-aware split (self-contained) ======
import numpy as np, pandas as pd, os, matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, median_absolute_error

# 0) Source data: prefer df if you already created it; otherwise fall back to merged
src = locals().get('df', locals().get('merged')).copy()

# 1) Build robust 'work' table (no hard dependency on a 'Country' column)
pm_feats = [c for c in ['PM25_Total_ugm3','PM25_Urban_ugm3','PM25_Rural_ugm3'] if c in src.columns]
target   = 'U5MR_per_1000'
id_candidates = ['Country_ISO3','Year','Country','Country_x','Country_y']
id_cols = [c for c in id_candidates if c in src.columns]
need_cols = list(dict.fromkeys(id_cols + [target] + pm_feats))
work = src[need_cols].copy()

# unify to a single 'Country' col (optional, for labels)
if 'Country' not in work.columns:
    for c in ['Country_x','Country_y']:
        if c in work.columns:
            work['Country'] = work[c]; break

# clean
work = work.dropna(subset=[target] + pm_feats)
for c in [target] + pm_feats:
    q1, q99 = work[c].quantile([0.01, 0.99])
    work[c] = work[c].clip(q1, q99)

print("Using columns:", work.columns.tolist(), "| rows:", len(work))

# 2) Time-aware split
train = work[work['Year'] <= 2016].copy()
test  = work[work['Year'] >= 2017].copy()
X_train, y_train = train[pm_feats], train[target]
X_test,  y_test  = test[pm_feats],  test[target]
print(f"Train {train['Year'].min()}–{train['Year'].max()} | Test {test['Year'].min()}–{test['Year'].max()}")
print("Features:", pm_feats)

# 3) Models
pre = ColumnTransformer([('num', StandardScaler(), pm_feats)], remainder='drop')
models = {
    'Ridge': (Ridge(random_state=42), {'model__alpha':[0.1,1,3,10]}),
    'Lasso': (Lasso(random_state=42, max_iter=10000), {'model__alpha':[0.001,0.01,0.1,1]}),
    'RF':    (RandomForestRegressor(n_estimators=600, random_state=42, n_jobs=-1),
              {'model__max_depth':[6,10,None], 'model__min_samples_leaf':[1,5,10]}),
    'GBR':   (GradientBoostingRegressor(random_state=42),
              {'model__n_estimators':[200,400], 'model__learning_rate':[0.05,0.1], 'model__max_depth':[2,3]})
}

results, best_models = [], {}
cv = KFold(n_splits=5, shuffle=True, random_state=42)
for name, (est, grid) in models.items():
    pipe = Pipeline([('pre', pre), ('model', est)])
    gs = GridSearchCV(pipe, grid, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
    gs.fit(X_train, y_train)
    best = gs.best_estimator_
    best_models[name] = best
    yhat = best.predict(X_test)
    results.append((name,
                    r2_score(y_test, yhat),
                    mean_absolute_error(y_test, yhat),
                    median_absolute_error(y_test, yhat),
                    gs.best_params_))
    print(f"{name}: R^2={results[-1][1]:.3f}  MAE={results[-1][2]:.2f}  MedAE={results[-1][3]:.2f}  {gs.best_params_}")

res_df = pd.DataFrame(results, columns=['Model','R2_test','MAE','MedAE','BestParams']).sort_values('R2_test', ascending=False)
display(res_df)

# 4) Winner details
winner = res_df.iloc[0]['Model']
best = best_models[winner]
print("Top model:", winner)

if winner in ['Ridge','Lasso']:
    scaler = best.named_steps['pre'].named_transformers_['num'].named_steps['scaler']
    coefs = pd.Series(best.named_steps['model'].coef_ / scaler.scale_, index=pm_feats).sort_values(key=abs, ascending=True)
    coefs.plot(kind='barh'); plt.title(f'{winner} coefficients (std-corrected)'); plt.tight_layout(); plt.show()
    imp_df = coefs.rename('coef').reset_index().rename(columns={'index':'feature'})
else:
    imps = pd.Series(best.named_steps['model'].feature_importances_, index=pm_feats).sort_values(ascending=True)
    imps.plot(kind='barh'); plt.title(f'{winner} feature importance'); plt.tight_layout(); plt.show()
    imp_df = imps.rename('importance').reset_index().rename(columns={'index':'feature'})

# 5) Residuals
yhat = best.predict(X_test)
plt.scatter(yhat, y_test - yhat, alpha=0.4); plt.axhline(0, ls='--')
plt.xlabel('Fitted'); plt.ylabel('Residual'); plt.title('Residuals vs Fitted'); plt.tight_layout(); plt.show()

# 6) Save
out_dir = "/content/drive/MyDrive/sdg3_airpollution_u5mr/data_final"
os.makedirs(out_dir, exist_ok=True)
res_df.to_csv(f"{out_dir}/predictive_results_PMonly.csv", index=False)
imp_df.to_csv(f"{out_dir}/feature_importance_PMonly.csv", index=False)
print("Saved metrics & importances to data_final/")

import os, requests, zipfile

base = "/content/drive/MyDrive/sdg3_airpollution_u5mr/data_raw"
os.makedirs(base, exist_ok=True)

def wb_download(indicator: str, dest_zip: str):
    url = f"https://api.worldbank.org/v2/en/indicator/{indicator}?downloadformat=csv"
    r = requests.get(url, stream=True, allow_redirects=True, timeout=120)
    r.raise_for_status()
    with open(dest_zip, "wb") as f:
        for chunk in r.iter_content(1024*64):
            if chunk: f.write(chunk)
    if not zipfile.is_zipfile(dest_zip):
        with open(dest_zip, "rb") as fh: head = fh.read(120)
        raise RuntimeError(f"{indicator} → not a ZIP (starts with {head[:40]!r}).")

# Try candidates in order
health_candidates = [
    ("SH.XPD.CHEX.PC.CD",    f"{base}/wb_health_exp_pc.zip"),   # current US$
    ("SH.XPD.CHEX.PC.PP.KD", f"{base}/wb_health_exp_pc.zip"),   # PPP, constant intl $
]
got = None
for code, path in health_candidates:
    try:
        if os.path.exists(path): os.remove(path)
        wb_download(code, path)
        got = code
        print(f"✅ Downloaded {code} → {os.path.basename(path)}")
        break
    except Exception as e:
        print(f"↪️  {code} failed: {e}")

if got is None:
    print("⚠️ Could not fetch a per-capita health series automatically. You can proceed without it or upload a ZIP manually from data.worldbank.org.")

import pandas as pd, zipfile, functools, numpy as np

def load_wb(path, col_name):
    with zipfile.ZipFile(path) as zf:
        names = [n for n in zf.namelist()
                 if n.lower().endswith(".csv")
                 and n.lower().startswith("api")
                 and "metadata" not in n.lower()]
        if not names:
            names = [n for n in zf.namelist() if n.lower().endswith(".csv")]
        with zf.open(names[0]) as f:
            df = pd.read_csv(f, skiprows=4, engine="python", on_bad_lines="skip", encoding="latin-1")
    df.columns = [c.strip() for c in df.columns]
    if "Country Code" not in df.columns:
        raise KeyError("No 'Country Code' column found.")
    df = df.rename(columns={"Country Code":"Country_ISO3"})
    year_cols = [c for c in df.columns if str(c).isdigit()]
    out = df.melt(id_vars=["Country_ISO3"], value_vars=year_cols,
                  var_name="Year", value_name=col_name)
    out["Year"] = pd.to_numeric(out["Year"], errors="coerce")
    out[col_name] = pd.to_numeric(out[col_name], errors="coerce")
    return out.dropna(subset=[col_name])

# Download (or keep) the other indicators
def safe_download(code, name):
    p = f"{base}/{name}.zip"
    if not os.path.exists(p):
        wb_download(code, p)
        print(f"✅ {code} → {name}.zip")
    return p

gdp_zip   = safe_download("NY.GDP.PCAP.KD",   "wb_gdp_percap_const")
urban_zip = safe_download("SP.URB.TOTL.IN.ZS","wb_urban_pct")
fert_zip  = safe_download("SP.DYN.TFRT.IN",   "wb_fertility")

ctrl_paths = [
    (gdp_zip,   "gdp_pc"),
    (urban_zip, "urban_pct"),
    (fert_zip,  "fertility"),
]
# Add health exp only if we actually got it
hx_path = f"{base}/wb_health_exp_pc.zip"
if os.path.exists(hx_path):
    ctrl_paths.append((hx_path, "hexp_pc"))

ctrls = [load_wb(p, c) for p,c in ctrl_paths]
controls = functools.reduce(lambda l,r: pd.merge(l,r, on=["Country_ISO3","Year"], how="outer"), ctrls)
print("Controls merged shape:", controls.shape)

# 'merged' is your WHO+UNICEF table built earlier
df_full = merged.merge(controls, on=["Country_ISO3","Year"], how="left")
print("Merged shape with controls:", df_full.shape)

# clip extremes + logs (only if present)
for c in ["gdp_pc","hexp_pc","U5MR_per_1000"]:
    if c in df_full.columns:
        q1,q99 = df_full[c].quantile([0.01,0.99])
        df_full[c] = df_full[c].clip(q1,q99)

if "gdp_pc" in df_full.columns:  df_full["log_gdp_pc"]  = np.log(df_full["gdp_pc"]  + 1)
if "hexp_pc" in df_full.columns: df_full["log_hexp_pc"] = np.log(df_full["hexp_pc"] + 1)

df_full[[c for c in ["Country_ISO3","Year","PM25_Total_ugm3","U5MR_per_1000","gdp_pc","hexp_pc","urban_pct","fertility"] if c in df_full.columns]].head()

base_feats = ['PM25_Total_ugm3','PM25_Urban_ugm3','PM25_Rural_ugm3',
              'log_gdp_pc','log_hexp_pc','urban_pct','fertility']
features = [c for c in base_feats if c in df_full.columns]

print("Using confounders:", features)
# then reuse your time-aware / LOCO code with `features` instead of pm-only columns

print("Total rows:", len(work))
print("Year range:", work["Year"].min(), "→", work["Year"].max())

cutoff = int(work["Year"].quantile(0.8))
print("Auto cutoff year =", cutoff)

print("Train rows:", (work["Year"] <= cutoff).sum())
print("Test rows:", (work["Year"] >  cutoff).sum())

# === Time-aware split: per-country last year as test ===
target = "U5MR_per_1000"

# Redefine features and work to ensure all columns are present
base_feats = ['PM25_Total_ugm3','PM25_Urban_ugm3','PM25_Rural_ugm3',
              'log_gdp_pc','log_hexp_pc','urban_pct','fertility']
features = [c for c in base_feats if c in df_full.columns]
work = df_full.dropna(subset=[target] + features).copy()


last_year_by_cty = work.groupby("Country_ISO3")["Year"].transform("max")
test_mask  = work["Year"].eq(last_year_by_cty)
test  = work[test_mask].copy()
train = work[~test_mask].copy()

print(f"per-country latest-year split -> train={len(train)}  test={len(test)}  "
      f"unique countries in test={test['Country_ISO3'].nunique()}")

Xtr, ytr = train[features], np.log1p(train[target].values)
Xte, yte = test[features],  np.log1p(test[target].values)

from sklearn.model_selection import train_test_split
train, test = train_test_split(work, test_size=0.2, random_state=42)
Xtr, ytr = train[features], np.log1p(train[target].values)
Xte, yte = test[features],  np.log1p(test[target].values)
print("Random split fallback ->", len(train), len(test))

# === Robust time-aware training with fallbacks ===
import os, numpy as np, pandas as pd, matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV, KFold, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

BASE = "/content/drive/MyDrive/sdg3_airpollution_u5mr"
DIR_FIG = f"{BASE}/reports/figures"; DIR_TAB = f"{BASE}/reports/tables"
os.makedirs(DIR_FIG, exist_ok=True); os.makedirs(DIR_TAB, exist_ok=True)

target = "U5MR_per_1000"
work = df_full.dropna(subset=[target] + features).copy()

# --- Split strategy: auto year cutoff -> per-country last year -> random ---
def build_splits(_work, _features):
    # try: 80% oldest years train, newest 20% test
    cutoff = int(_work["Year"].quantile(0.8))
    tr = _work[_work["Year"] <= cutoff].copy()
    te = _work[_work["Year"] >  cutoff].copy()
    if len(te) > 0:
        return tr, te, f"quantile_cutoff={cutoff}"

    # fallback: per-country latest year as test
    last_year = _work.groupby("Country_ISO3")["Year"].transform("max")
    te = _work[_work["Year"].eq(last_year)].copy()
    tr = _work[~_work["Year"].eq(last_year)].copy()
    if len(te) > 0:
        return tr, te, "per_country_latest_year"

    # final fallback: random split
    tr, te = train_test_split(_work, test_size=0.2, random_state=42)
    return tr.copy(), te.copy(), "random_80_20"

train, test, split_used = build_splits(work, features)
print(f"Split used: {split_used} | train={len(train)} | test={len(test)} | "
      f"years train {train['Year'].min()}–{train['Year'].max()} | years test {test['Year'].min()}–{test['Year'].max()}")

# --- Data matrices (log target) ---
Xtr, ytr = train[features], np.log1p(train[target].values)
Xte, yte = test[features],  np.log1p(test[target].values)
print("Shapes:", Xtr.shape, Xte.shape)  # make sure test > 0

# --- Models & grids ---
pre = ColumnTransformer([('num', StandardScaler(), features)], remainder='drop')
models = {
    'Ridge': (Ridge(), {'model__alpha':[0.1,1,3,10,30]}),
    'Lasso': (Lasso(max_iter=10000), {'model__alpha':[0.001,0.01,0.1,1,3]}),
    'GBR':   (GradientBoostingRegressor(random_state=42),
              {'model__n_estimators':[300,600,1000],'model__learning_rate':[0.03,0.05,0.08],'model__max_depth':[2,3,4]}),
    'RF':    (RandomForestRegressor(n_estimators=600, random_state=42, n_jobs=-1),
              {'model__max_depth':[None,6,10], 'model__min_samples_leaf':[1,2,4]}),
}

rows, best_models = [], {}
for name, (est, grid) in models.items():
    pipe = Pipeline([('pre', pre), ('model', est)])
    gs = GridSearchCV(pipe, grid, scoring='neg_mean_absolute_error', cv=5, n_jobs=-1)
    gs.fit(Xtr, ytr)
    best = gs.best_estimator_
    best_models[name] = best
    yhat = np.expm1(best.predict(Xte))
    yt   = np.expm1(yte)
    rows.append({'Model': name,
                 'R2': r2_score(yt, yhat),
                 'MAE': mean_absolute_error(yt, yhat),
                 'RMSE': mean_squared_error(yt, yhat) ** 0.5,
                 'BestParams': gs.best_params_})
res = pd.DataFrame(rows).sort_values('MAE')
display(res)
res.to_csv(f"{DIR_TAB}/time_aware_results_w_controls.csv", index=False)

# scatter for best model
winner = res.iloc[0]['Model']
yhat = np.expm1(best_models[winner].predict(Xte)); yt = np.expm1(yte)
plt.figure(figsize=(6,6))
plt.scatter(yt, yhat, alpha=0.6)
m = max(yt.max(), yhat.max())*1.05; plt.plot([0,m],[0,m])
plt.xlabel("True U5MR"); plt.ylabel("Predicted U5MR")
plt.title(f"{split_used}: {winner} with confounders")
plt.tight_layout(); plt.savefig(f"{DIR_FIG}/time_scatter_w_controls.png", dpi=200)
print("Saved:", f"{DIR_TAB}/time_aware_results_w_controls.csv", "and", f"{DIR_FIG}/time_scatter_w_controls.png")

from sklearn.metrics import mean_absolute_error, mean_squared_error
import pandas as pd, numpy as np

target = "U5MR_per_1000"
yt = np.expm1(yte)
yhat_best = np.expm1(best_models[winner].predict(Xte)).ravel()

# Baselines (country mean + last observed)
mean_by_cty = train.groupby('Country_ISO3')[target].mean()
pred_mean = test['Country_ISO3'].map(mean_by_cty).fillna(train[target].mean())

last_tr = train.sort_values(['Country_ISO3','Year']).groupby('Country_ISO3')[target].last()
pred_last = test['Country_ISO3'].map(last_tr).fillna(train[target].median())

def ev(name, pred):
    return {'Name': name,
            'MAE': mean_absolute_error(yt, pred),
            'RMSE': mean_squared_error(yt, pred)**0.5}

tbl = pd.DataFrame([
    ev("Baseline: Country mean", pred_mean),
    ev("Baseline: Last observed", pred_last),
    ev(f"Best ML ({winner})", yhat_best)
])
display(tbl)
tbl.to_csv("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/tables/baselines_vs_ml_w_controls.csv", index=False)

from sklearn.model_selection import GroupKFold
import xgboost as xgb, pandas as pd, numpy as np, matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

work = df_full.dropna(subset=[target] + features).copy()
X = work[features].copy()
y = np.log1p(work[target].values)
groups = work['Country_ISO3'].values

gkf = GroupKFold(n_splits=len(np.unique(groups)))
xgbm = xgb.XGBRegressor(
    n_estimators=700, max_depth=4, learning_rate=0.05,
    subsample=0.9, colsample_bytree=0.9, reg_lambda=1.0,
    objective='reg:squarederror', random_state=42, n_jobs=-1
)

rows=[]
for tr, te in gkf.split(X, y, groups):
    xgbm.fit(X.iloc[tr], y[tr])
    yhat = np.expm1(xgbm.predict(X.iloc[te])); yt = np.expm1(y[te])
    iso3 = work.iloc[te].Country_ISO3.iloc[0]
    rows.append({'ISO3': iso3,
                 'MAE': mean_absolute_error(yt,yhat),
                 'RMSE': mean_squared_error(yt,yhat)**0.5,
                 'R2': r2_score(yt,yhat)})
loco = pd.DataFrame(rows).sort_values('MAE')
loco.to_csv("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/tables/loco_country_scores_w_controls.csv", index=False)

plt.figure(figsize=(7,10))
plt.barh(loco.ISO3, loco.MAE); plt.gca().invert_yaxis()
plt.xlabel("MAE (U5MR)"); plt.title("LOCO MAE by held-out country (with confounders)")
plt.tight_layout(); plt.savefig("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/figures/loco_mae_by_country_w_controls.png", dpi=200)

top10 = loco.nsmallest(10, 'MAE')  # lowest errors
top10.to_csv("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/tables/loco_top10_best_mae.csv", index=False)

plt.figure(figsize=(7,6))
plt.barh(top10.ISO3, top10.MAE); plt.gca().invert_yaxis()
plt.xlabel("MAE (U5MR)"); plt.title("Top 10 (lowest MAE) LOCO by country")
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/figures/loco_top10_best_mae.png", dpi=200)

worst10 = loco.nlargest(10, 'MAE')
worst10.to_csv("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/tables/loco_top10_worst_mae.csv", index=False)

plt.figure(figsize=(7,6))
plt.barh(worst10.ISO3, worst10.MAE); plt.gca().invert_yaxis()
plt.xlabel("MAE (U5MR)"); plt.title("Top 10 (highest MAE) LOCO by country")
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/figures/loco_top10_worst_mae.png", dpi=200)

import shap, numpy as np, matplotlib.pyplot as plt
X_all = work[features]; y_all = np.log1p(work[target].values)

xgb_all = xgb.XGBRegressor(
    n_estimators=700, max_depth=4, learning_rate=0.05,
    subsample=0.9, colsample_bytree=0.9, reg_lambda=1.0,
    objective='reg:squarederror', random_state=42, n_jobs=-1
).fit(X_all, y_all)

expl = shap.TreeExplainer(xgb_all)
Xs = X_all.sample(min(2000, len(X_all)), random_state=42)
sv = expl(Xs)

shap.plots.beeswarm(sv, show=False)
plt.title("SHAP beeswarm (with confounders)")
plt.tight_layout(); plt.savefig("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/figures/shap_beeswarm_w_controls.png", dpi=200)

shap.plots.bar(sv, show=False)
plt.title("SHAP mean |importance|")
plt.tight_layout(); plt.savefig("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/figures/shap_bar_w_controls.png", dpi=200)

# PD-style curve
pm = 'PM25_Total_ugm3'
grid = np.linspace(X_all[pm].quantile(0.05), X_all[pm].quantile(0.95), 40)
X_ref = X_all.median().to_frame().T.loc[np.zeros(len(grid), dtype=int)].copy()
X_ref[pm] = grid
pd_y = np.expm1(xgb_all.predict(X_ref))
plt.figure(figsize=(6,4))
plt.plot(grid, pd_y)
plt.xlabel("PM2.5 Total (µg/m³)"); plt.ylabel("Predicted U5MR (per 1,000)")
plt.title("Partial-dependence style curve for PM2.5")
plt.tight_layout(); plt.savefig("/content/drive/MyDrive/sdg3_airpollution_u5mr/reports/figures/pdcurve_pm25_w_controls.png", dpi=200)